### ISSUE TITLE
[Tracking] - Web UI V1 Roadmap

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#137]
## Background

The Prysm Web UI is still in beta given our team has not offered dedicated maintenance to the project. Given it has become so popular thanks to tools such as Avado and Dappnode, we need to place more emphasis on the web UI as a useful tool for stakers that is less bug prone and does its job well. As such, we are outlining the following roadmap to promote the web UI to v1 along with our vision for the project.

The two goals of the Prysm web UI are:

1. To provide a point and click experience to managing your Prysm validator as closely as possible as you can with the Prysm CLI
2. To provide a visual interface to understand details about your running validator process and the eth2 network, such as peers, CPU and RAM use, logs, the validating public keys in your wallet, your validator balances, and more

That is, we want stakers to do **everything they can with the command line** for their validator via a simple web interface. Requirements to meet this goal are:

1. Ease of use and simplicity to configure the web interface
2. No complicated use of passwords. Simply be prompted to type in your password whenever you perform an activity in the interface that does something such as export your accounts, create a new account, etc.
3. Easy to understand error messages, with ability to report bugs to the team if desired via a button click when they happen
4. Prevent commonly reported UI bugs and make the experience solid for all stakers

To accomplish this, we will start by simplifying the interface and removing some extraneous features that exist today which do not guide us toward these goals. 

## Feature Refactoring & Simplification

- [x] Remove usage of passwords in the web UI. Only ask for passwords via a pop-up when you are performing some sensitive action such as exporting an account. This will greatly simplify the security of the interface and allow for a smoother user experience
- [x] Remove performance graphs from the front-page as the data is expensive to query for more than a few epochs and is often times not accurate

## New Features

- [x] Ability to see Prysm's latest release with a quick gist of the features
- [x] Ability to see current version in use
- [ ] Ability to see avg RAM and CPU utilization and disk usage
- [x] Allow for all wallet commands
- [x] Allow for all account commands
- [ ] Allow for all slashing protection commands
- [ ] Ability to report seen errors to the team (optional)

## Nice to Have

- [ ] Ability to see flags in use

**Comment by james-prysm** [comment]
Closing this issue and migrating some objectives to v2
