### ISSUE TITLE
[Tracking] - Web UI V2 Roadmap 

### ISSUE THREAD

**Issue by james-prysm** [prysmaticlabs/prysm-web-ui#220]
# Background
As part of Prysm V1.0 we were able to address a lot of existing issues with Prysm and made it more compatible with the Altair fork.
Prysm Web UI 2.0 brings more features from the CLI and provides the necessary features for the merge. With the release of the keymanager API standards  https://github.com/ethereum/keymanager-APIs we have provided the community with a way to build their own UI for Prysm. Prysm will continue to support the Web UI but will focus on core features that bring a graphical interface alternative to the CLI.

## Analysis

- [ ] ~~Validator activation UI~~
- [ ] ~~Dashboard UX~~

## Tech Debt/ Refactors

- [x] upgrading dependencies to reduce staleness of angular project and patch vulnerabilities

## New Features

- [x] Keymanager API Import ( with slashing protection import)
- [x] Keymanager API Delete (with slashing protection export)
- [x] UI for reexport slashing protection
- [ ] ~~Keymanager API List public keys~~
- [x] Keymanager API List Fee Recipient 
- [x] Keymanager API Set Fee Recipient 
- [x] Keymanager API Delete Fee Recipient 
- [ ] ~~Browser private variables~~

## Post V2
- [ ] deprecate old APIs that are now unused
