### ISSUE TITLE
Tracking MVP Release

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#42]
This is a tracking issue for the MVP release of the Prysm Web UI and what we should consider a requirement before announcing to users and having them beta test the functionality.

- [x] Ability to onboard users that came from launchpad by either (a) recovering their HD wallet, or (b) importing keystores files via the web interface
- [x] Ability to login after one has completed onboarding by using the wallet password
- [x] Ability to see a nice dashboard summarizing the state of their validators, their beacon node connection, and info such as chain participation and the current validator queue
- [x] Ability to see a nice chart of the recent epoch percentage gains and/or losses #31 
- [x] Ability to change wallet password (backend done and frontend done, just need to call the backend function from angular)
- [x] Ability to see beacon node + validator client logs from the web UI via websockets
- [x] Ability to see all accounts in a user's wallet along with their important information such as recent performance, activation status, balance, etc.
- [x] Ability to filter accounts in a nice table with relevant fields
- [x] Create new accounts, backup, and remove from the wallet via the web UI
- [x] Ability to see deposit data from the web UI with instructions on how to submit the deposit to metamask
- [x] Ability to see basic wallet information such as path, type of wallet, etc.
- [x] Wrap up the logs stream page design
- [x] Show deposit data in onboarding wizard steps

Small, but important odds and ends
- [x] Cannot currently login if user already has a wallet but **has never used** the web UI before
- [x] Test out "default data", such as a wallet with 1 account or no active validators
- [x] Responsive navbar (currently, the sidenav disappears on mobile but we need a way for users to navigate)
- [x] Make breadcrumb component functional
- [x] Mark the metrics page as coming soon
- [x] Do not disable button in the login page

Out of scope
- Depositing via the web UI will not be implemented for security reasons, instead suggesting users to use the launchpad as much as possible
- Implementation of the metrics page
- Advanced state management via NgRx to cache requests for recent epoch balances
