### ISSUE TITLE
Tracking Beta Release Bug Fixes

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/prysm-web-ui#60]
- [x] Add info on login page why the create/import wallet is not accessible anymore
- [x] Old password should be entered before changing the password and be validated in backend
- [x] Wallet Information --> How can I change my password? - the link in the answer to this question is incorrect
- [x] Make the JSON preview larger when creating accounts
- [x] Enforce at least 1 account when creating accounts instead of 0
- [x] Open the Join the Testnet link in a new tab
- [x] JWT expiration isn't handled well
- [x] Allow importing of zip files
- [x] Some tooltip in the wallet details page says "hello"
- [x] Validator got slashed, still said active in the UI. Feature request: offer user neverslashed.com to review to prevent slashings
- [x] Diagnose error: {error: "Could not validate password input", code: 3, message: "Could not validate password input"}, yet password was created in backend despite failing validity
- [x] Return slashed status from backend in list validator balances
- [x] Display total balance in main dashboard
- [x] Account deletion is broken (what if I am left with 0 accounts?)
- [x] Users shouldn't be able to copy paste mnemonic
- [x] Break the text in "how are my private keys stored" into paragraphs
- [x] `Could not validate password input` is not specific enough as a backend error response
- [x] Flickering if password is wrong and clicked continue
- [x] Toasts should be red for error messages
